/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calc;

import java.awt.Toolkit;

/**
 *
 * @author abdal
 */
public class ThreeMultipication extends javax.swing.JFrame {

    /**
     * Creates new form ThreeMultipication
     */
    public ThreeMultipication() {
        imageIcon();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldColumns2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldColumns1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldColumns11 = new javax.swing.JTextField();
        jTextFieldColumns10 = new javax.swing.JTextField();
        jTextFieldColumns13 = new javax.swing.JTextField();
        jTextFieldColumns14 = new javax.swing.JTextField();
        jTextFieldColumns5 = new javax.swing.JTextField();
        jTextFieldColumns4 = new javax.swing.JTextField();
        jTextFieldColumns3 = new javax.swing.JTextField();
        jTextFieldColumns6 = new javax.swing.JTextField();
        jTextFieldColumns7 = new javax.swing.JTextField();
        jTextFieldColumns8 = new javax.swing.JTextField();
        jTextFieldColumns9 = new javax.swing.JTextField();
        jTextFieldColumns17 = new javax.swing.JTextField();
        jTextFieldColumns16 = new javax.swing.JTextField();
        jTextFieldColumns12 = new javax.swing.JTextField();
        jTextFieldColumns15 = new javax.swing.JTextField();
        jTextFieldColumns18 = new javax.swing.JTextField();
        jTextFieldColumnsResult1 = new javax.swing.JTextField();
        jTextFieldColumnsResult2 = new javax.swing.JTextField();
        jTextFieldColumnsResult3 = new javax.swing.JTextField();
        jTextFieldColumnsResult6 = new javax.swing.JTextField();
        jTextFieldColumnsresult4 = new javax.swing.JTextField();
        jTextFieldColumnsResult5 = new javax.swing.JTextField();
        jTextFieldColumnsResult7 = new javax.swing.JTextField();
        jTextFieldColumnsResult8 = new javax.swing.JTextField();
        jTextFieldColumnsResult9 = new javax.swing.JTextField();
        jButtonResult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 182, 26));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Your Dimension");

        jLabel2.setForeground(new java.awt.Color(255, 182, 26));
        jLabel2.setText("Matrix1");

        jLabel3.setForeground(new java.awt.Color(255, 182, 26));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Matrix2");

        jTextFieldColumns2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns2ActionPerformed(evt);
            }
        });
        jTextFieldColumns2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns2KeyPressed(evt);
            }
        });

        jButton1.setText("Main page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back <=");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextFieldColumns1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns1ActionPerformed(evt);
            }
        });
        jTextFieldColumns1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns1KeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextFieldColumns11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns11ActionPerformed(evt);
            }
        });
        jTextFieldColumns11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns11KeyPressed(evt);
            }
        });

        jTextFieldColumns10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns10ActionPerformed(evt);
            }
        });
        jTextFieldColumns10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns10KeyPressed(evt);
            }
        });

        jTextFieldColumns13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns13ActionPerformed(evt);
            }
        });
        jTextFieldColumns13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns13KeyPressed(evt);
            }
        });

        jTextFieldColumns14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns14ActionPerformed(evt);
            }
        });
        jTextFieldColumns14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns14KeyPressed(evt);
            }
        });

        jTextFieldColumns5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns5ActionPerformed(evt);
            }
        });
        jTextFieldColumns5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns5KeyPressed(evt);
            }
        });

        jTextFieldColumns4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns4ActionPerformed(evt);
            }
        });
        jTextFieldColumns4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns4KeyPressed(evt);
            }
        });

        jTextFieldColumns3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns3ActionPerformed(evt);
            }
        });
        jTextFieldColumns3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns3KeyPressed(evt);
            }
        });

        jTextFieldColumns6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns6ActionPerformed(evt);
            }
        });
        jTextFieldColumns6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns6KeyPressed(evt);
            }
        });

        jTextFieldColumns7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns7ActionPerformed(evt);
            }
        });
        jTextFieldColumns7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns7KeyPressed(evt);
            }
        });

        jTextFieldColumns8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns8ActionPerformed(evt);
            }
        });
        jTextFieldColumns8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns8KeyPressed(evt);
            }
        });

        jTextFieldColumns9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns9ActionPerformed(evt);
            }
        });
        jTextFieldColumns9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns9KeyPressed(evt);
            }
        });

        jTextFieldColumns17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns17ActionPerformed(evt);
            }
        });
        jTextFieldColumns17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns17KeyPressed(evt);
            }
        });

        jTextFieldColumns16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns16ActionPerformed(evt);
            }
        });
        jTextFieldColumns16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns16KeyPressed(evt);
            }
        });

        jTextFieldColumns12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns12ActionPerformed(evt);
            }
        });
        jTextFieldColumns12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns12KeyPressed(evt);
            }
        });

        jTextFieldColumns15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns15ActionPerformed(evt);
            }
        });
        jTextFieldColumns15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns15KeyPressed(evt);
            }
        });

        jTextFieldColumns18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumns18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumns18ActionPerformed(evt);
            }
        });
        jTextFieldColumns18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumns18KeyPressed(evt);
            }
        });

        jTextFieldColumnsResult1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumnsResult1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumnsResult1ActionPerformed(evt);
            }
        });
        jTextFieldColumnsResult1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumnsResult1KeyPressed(evt);
            }
        });

        jTextFieldColumnsResult2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumnsResult2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumnsResult2ActionPerformed(evt);
            }
        });
        jTextFieldColumnsResult2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumnsResult2KeyPressed(evt);
            }
        });

        jTextFieldColumnsResult3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumnsResult3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumnsResult3ActionPerformed(evt);
            }
        });
        jTextFieldColumnsResult3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumnsResult3KeyPressed(evt);
            }
        });

        jTextFieldColumnsResult6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumnsResult6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumnsResult6ActionPerformed(evt);
            }
        });
        jTextFieldColumnsResult6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumnsResult6KeyPressed(evt);
            }
        });

        jTextFieldColumnsresult4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumnsresult4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumnsresult4ActionPerformed(evt);
            }
        });
        jTextFieldColumnsresult4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumnsresult4KeyPressed(evt);
            }
        });

        jTextFieldColumnsResult5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumnsResult5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumnsResult5ActionPerformed(evt);
            }
        });
        jTextFieldColumnsResult5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumnsResult5KeyPressed(evt);
            }
        });

        jTextFieldColumnsResult7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumnsResult7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumnsResult7ActionPerformed(evt);
            }
        });
        jTextFieldColumnsResult7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumnsResult7KeyPressed(evt);
            }
        });

        jTextFieldColumnsResult8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumnsResult8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumnsResult8ActionPerformed(evt);
            }
        });
        jTextFieldColumnsResult8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumnsResult8KeyPressed(evt);
            }
        });

        jTextFieldColumnsResult9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColumnsResult9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumnsResult9ActionPerformed(evt);
            }
        });
        jTextFieldColumnsResult9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldColumnsResult9KeyPressed(evt);
            }
        });

        jButtonResult.setText("Result");
        jButtonResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldColumns1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumns4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumns7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldColumns2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumns5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumns8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldColumns3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumns6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumns9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldColumns10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumns13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumns16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldColumns11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumns14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumns17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldColumns15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumns12)
                    .addComponent(jTextFieldColumns18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jButtonResult, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldColumnsResult1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumnsresult4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumnsResult7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldColumnsResult2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumnsResult5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumnsResult8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldColumnsResult3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumnsResult6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColumnsResult9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jTextFieldColumns3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldColumns6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldColumns9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jTextFieldColumns1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldColumns4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldColumns7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldColumns12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldColumns15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldColumns18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldColumns10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldColumns11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldColumns13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldColumns16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jTextFieldColumns14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldColumns17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldColumns2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldColumns5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldColumns8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonResult)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldColumnsResult3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldColumnsResult6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldColumnsResult9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldColumnsResult1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldColumnsResult2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldColumnsresult4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldColumnsResult5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldColumnsResult7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldColumnsResult8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldColumns2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns2ActionPerformed

    private void jTextFieldColumns2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns2KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns2.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns2.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns2KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        welcome_page wp = new welcome_page();
        wp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        EnterArrayFirst a1 = new EnterArrayFirst();
        a1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldColumns1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns1ActionPerformed

    }//GEN-LAST:event_jTextFieldColumns1ActionPerformed

    private void jTextFieldColumns1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns1KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns1.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns1.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns1KeyPressed

    private void jTextFieldColumns11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns11ActionPerformed

    private void jTextFieldColumns11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns11KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns11.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns11.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns11KeyPressed

    private void jTextFieldColumns10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns10ActionPerformed

    private void jTextFieldColumns10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns10KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns10.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns10.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns10KeyPressed

    private void jTextFieldColumns13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns13ActionPerformed

    private void jTextFieldColumns13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns13KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns13.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns13.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns13KeyPressed

    private void jTextFieldColumns14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns14ActionPerformed

    private void jTextFieldColumns14KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns14KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns14.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns14.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns14KeyPressed

    private void jTextFieldColumns5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns5ActionPerformed

    private void jTextFieldColumns5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns5KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns5.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns5.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns5KeyPressed

    private void jTextFieldColumns4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns4ActionPerformed

    private void jTextFieldColumns4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns4KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns4.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns4.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns4KeyPressed

    private void jTextFieldColumns3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns3ActionPerformed

    private void jTextFieldColumns3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns3KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns3.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns3.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns3KeyPressed

    private void jTextFieldColumns6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns6ActionPerformed

    private void jTextFieldColumns6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns6KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns6.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns6.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns6KeyPressed

    private void jTextFieldColumns7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns7ActionPerformed

    private void jTextFieldColumns7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns7KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns7.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns7.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns7KeyPressed

    private void jTextFieldColumns8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns8ActionPerformed

    private void jTextFieldColumns8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns8KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns8.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns8.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns8KeyPressed

    private void jTextFieldColumns9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns9ActionPerformed

    private void jTextFieldColumns9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns9KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns9.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns9.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns9KeyPressed

    private void jTextFieldColumns17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns17ActionPerformed

    private void jTextFieldColumns17KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns17KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns17.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns17.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns17KeyPressed

    private void jTextFieldColumns16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns16ActionPerformed

    private void jTextFieldColumns16KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns16KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns16.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns16.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns16KeyPressed

    private void jTextFieldColumns12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns12ActionPerformed

    private void jTextFieldColumns12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns12KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns12.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns12.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns12KeyPressed

    private void jTextFieldColumns15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns15ActionPerformed

    private void jTextFieldColumns15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns15KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns15.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns15.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns15KeyPressed

    private void jTextFieldColumns18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumns18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumns18ActionPerformed

    private void jTextFieldColumns18KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumns18KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            jTextFieldColumns18.setEditable(false);
            jLabel4.setText("Please Enter Numbers only !");
        }else{
            jTextFieldColumns18.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldColumns18KeyPressed

    private void jTextFieldColumnsResult1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumnsResult1ActionPerformed

    private void jTextFieldColumnsResult1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult1KeyPressed
        jTextFieldColumnsResult1.setEditable(false);
    }//GEN-LAST:event_jTextFieldColumnsResult1KeyPressed

    private void jTextFieldColumnsResult2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumnsResult2ActionPerformed

    private void jTextFieldColumnsResult2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult2KeyPressed
        jTextFieldColumnsResult2.setEditable(false);
    }//GEN-LAST:event_jTextFieldColumnsResult2KeyPressed

    private void jTextFieldColumnsResult3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumnsResult3ActionPerformed

    private void jTextFieldColumnsResult3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult3KeyPressed
        jTextFieldColumnsResult3.setEditable(false);
    }//GEN-LAST:event_jTextFieldColumnsResult3KeyPressed

    private void jTextFieldColumnsResult6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumnsResult6ActionPerformed

    private void jTextFieldColumnsResult6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult6KeyPressed
        jTextFieldColumnsResult6.setEditable(false);
    }//GEN-LAST:event_jTextFieldColumnsResult6KeyPressed

    private void jTextFieldColumnsresult4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumnsresult4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumnsresult4ActionPerformed

    private void jTextFieldColumnsresult4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumnsresult4KeyPressed
        jTextFieldColumnsresult4.setEditable(false);
    }//GEN-LAST:event_jTextFieldColumnsresult4KeyPressed

    private void jTextFieldColumnsResult5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult5ActionPerformed

    }//GEN-LAST:event_jTextFieldColumnsResult5ActionPerformed

    private void jTextFieldColumnsResult5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult5KeyPressed
        jTextFieldColumnsResult5.setEditable(false);
    }//GEN-LAST:event_jTextFieldColumnsResult5KeyPressed

    private void jTextFieldColumnsResult7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumnsResult7ActionPerformed

    private void jTextFieldColumnsResult7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult7KeyPressed
        jTextFieldColumnsResult7.setEditable(false);
    }//GEN-LAST:event_jTextFieldColumnsResult7KeyPressed

    private void jTextFieldColumnsResult8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumnsResult8ActionPerformed

    private void jTextFieldColumnsResult8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult8KeyPressed
        jTextFieldColumnsResult8.setEditable(false);
    }//GEN-LAST:event_jTextFieldColumnsResult8KeyPressed

    private void jTextFieldColumnsResult9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumnsResult9ActionPerformed

    private void jTextFieldColumnsResult9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColumnsResult9KeyPressed
        jTextFieldColumnsResult9.setEditable(false);
    }//GEN-LAST:event_jTextFieldColumnsResult9KeyPressed

    private void jButtonResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultActionPerformed
        int a = Integer.parseInt(jTextFieldColumns1.getText());
        int b = Integer.parseInt(jTextFieldColumns2.getText());
        int c1 = Integer.parseInt(jTextFieldColumns3.getText());
        int d = Integer.parseInt(jTextFieldColumns4.getText());
        int e = Integer.parseInt(jTextFieldColumns5.getText());
        int f = Integer.parseInt(jTextFieldColumns6.getText());
        int g = Integer.parseInt(jTextFieldColumns7.getText());
        int h = Integer.parseInt(jTextFieldColumns8.getText());
        int i = Integer.parseInt(jTextFieldColumns9.getText());
        int j = Integer.parseInt(jTextFieldColumns10.getText());
        int k = Integer.parseInt(jTextFieldColumns11.getText());
        int l = Integer.parseInt(jTextFieldColumns12.getText());
        int m = Integer.parseInt(jTextFieldColumns13.getText());
        int n = Integer.parseInt(jTextFieldColumns14.getText());
        int o = Integer.parseInt(jTextFieldColumns15.getText());
        int p = Integer.parseInt(jTextFieldColumns16.getText());
        int q = Integer.parseInt(jTextFieldColumns17.getText());
        int t = Integer.parseInt(jTextFieldColumns18.getText());

        int a1 =(a*j)+(b*m)+(c1*p);
        int a2 =(a*k)+(b*n)+(c1*q);
        int a3 =(a*l)+(b*o)+(c1*t);
        int a4 =(d*j)+(e*m)+(f*p);
        int a5 =(d*k)+(e*n)+(f*q);
        int a6 =(d*l)+(e*o)+(f*t);
        int a7 =(g*j)+(h*m)+(i*p);
        int a8 =(g*k)+(h*n)+(i*q);
        int a9 =(g*l)+(h*o)+(i*t);
        //        int r;
        //        int c;
        //        r =Integer.parseInt(EnterArrayFirst.jTextFieldRows.getText());
        //        c =Integer.parseInt(EnterArrayFirst.jTextFieldColumnn.getText());
        //        int[][]x = new int [r][c];
        //        int[][]y = new int [r][c];
        //        int[][]z;
        //        z = new int [r][c];
        jTextFieldColumnsResult1.setText(a1+"");
        jTextFieldColumnsResult2.setText(a2+"");
        jTextFieldColumnsResult3.setText(a3+"");
        jTextFieldColumnsresult4.setText(a4+"");
        jTextFieldColumnsResult5.setText(a5+"");
        jTextFieldColumnsResult6.setText(a6+"");
        jTextFieldColumnsResult7.setText(a7+"");
        jTextFieldColumnsResult8.setText(a8+"");
        jTextFieldColumnsResult9.setText(a9+"");
    }//GEN-LAST:event_jButtonResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThreeMultipication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThreeMultipication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThreeMultipication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThreeMultipication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThreeMultipication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private static javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jTextFieldColumns1;
    public static javax.swing.JTextField jTextFieldColumns10;
    public static javax.swing.JTextField jTextFieldColumns11;
    public static javax.swing.JTextField jTextFieldColumns12;
    public static javax.swing.JTextField jTextFieldColumns13;
    public static javax.swing.JTextField jTextFieldColumns14;
    public static javax.swing.JTextField jTextFieldColumns15;
    public static javax.swing.JTextField jTextFieldColumns16;
    public static javax.swing.JTextField jTextFieldColumns17;
    public static javax.swing.JTextField jTextFieldColumns18;
    public static javax.swing.JTextField jTextFieldColumns2;
    public static javax.swing.JTextField jTextFieldColumns3;
    public static javax.swing.JTextField jTextFieldColumns4;
    public static javax.swing.JTextField jTextFieldColumns5;
    public static javax.swing.JTextField jTextFieldColumns6;
    public static javax.swing.JTextField jTextFieldColumns7;
    public static javax.swing.JTextField jTextFieldColumns8;
    public static javax.swing.JTextField jTextFieldColumns9;
    private javax.swing.JTextField jTextFieldColumnsResult1;
    private javax.swing.JTextField jTextFieldColumnsResult2;
    private javax.swing.JTextField jTextFieldColumnsResult3;
    private javax.swing.JTextField jTextFieldColumnsResult5;
    private javax.swing.JTextField jTextFieldColumnsResult6;
    private javax.swing.JTextField jTextFieldColumnsResult7;
    private javax.swing.JTextField jTextFieldColumnsResult8;
    private javax.swing.JTextField jTextFieldColumnsResult9;
    private javax.swing.JTextField jTextFieldColumnsresult4;
    // End of variables declaration//GEN-END:variables
    private void imageIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
}
